export const wordsFirstPack = [
  { translatedWord: 'из', translation: 'from', learned: false },
  { translatedWord: 'к', translation: 'to', learned: false },
  { translatedWord: 'и', translation: 'and', learned: false },
  { translatedWord: 'в', translation: 'in', learned: false },
  { translatedWord: 'для', translation: 'for', learned: false },
  { translatedWord: 'есть(он)', translation: 'is', learned: false },
  { translatedWord: 'это', translation: 'this is', learned: false },
  { translatedWord: 'на', translation: 'on', learned: false },
  { translatedWord: 'сказал', translation: 'said', learned: false },
  { translatedWord: 'с', translation: 'with', learned: false },
  { translatedWord: 'быть', translation: 'be', learned: false },
  { translatedWord: 'был', translation: 'was', learned: false },
  { translatedWord: 'с помощью', translation: 'by', learned: false },
  { translatedWord: 'как', translation: 'as', learned: false },
  { translatedWord: 'есть(они, вы, ты, мы)', translation: 'are', learned: false },
  { translatedWord: 'в (в школе)', translation: 'at', learned: false },
  { translatedWord: 'от', translation: 'from', learned: false },
  { translatedWord: 'имеет', translation: 'has', learned: false },
  { translatedWord: 'иметь', translation: 'have', learned: false },
  { translatedWord: 'будет', translation: 'will be', learned: false },
  { translatedWord: 'или', translation: 'or', learned: false },
  { translatedWord: 'он', translation: 'he', learned: false },
  { translatedWord: 'нет', translation: 'not', learned: false },
  { translatedWord: 'были', translation: 'were', learned: false },
  { translatedWord: 'который', translation: 'which', learned: false },
  { translatedWord: 'это', translation: 'this', learned: false },
  { translatedWord: 'но', translation: 'but', learned: false },
  { translatedWord: 'может (про способность)', translation: 'can', learned: false },
  { translatedWord: 'больше', translation: 'more', learned: false },
  { translatedWord: 'его', translation: 'his', learned: false },
  { translatedWord: 'был бы', translation: 'would be', learned: false },
  { translatedWord: 'о', translation: 'about', learned: false },
  { translatedWord: 'их', translation: 'their', learned: false },
  { translatedWord: 'также', translation: 'also', learned: false },
  { translatedWord: 'они', translation: 'they', learned: false },
  { translatedWord: 'миллион', translation: 'million', learned: false },
  { translatedWord: 'имел', translation: 'had', learned: false },
  { translatedWord: 'чем (больше чем он)', translation: 'than', learned: false },
  { translatedWord: 'вверх', translation: 'up', learned: false },
  { translatedWord: 'кто', translation: 'who', learned: false },
  { translatedWord: 'в', translation: 'In', learned: false },
  { translatedWord: 'один', translation: 'one', learned: false },
  { translatedWord: 'вы', translation: 'you', learned: false },
  { translatedWord: 'новый', translation: 'new', learned: false },
  { translatedWord: 'я', translation: 'I', learned: false },
  { translatedWord: 'другой', translation: 'another', learned: false },
  { translatedWord: 'год', translation: 'year', learned: false },
  { translatedWord: 'все', translation: 'all', learned: false },
  { translatedWord: 'два', translation: 'two', learned: false },
  { translatedWord: 'но', translation: 'But', learned: false },
  { translatedWord: 'компания', translation: 'company', learned: false },
  { translatedWord: 'господин', translation: 'Mr.', learned: false },
  { translatedWord: 'система', translation: 'system', learned: false },
  { translatedWord: 'некоторые', translation: 'some', learned: false },
  { translatedWord: 'когда', translation: 'when', learned: false },
  { translatedWord: 'вне', translation: 'out', learned: false },
  { translatedWord: 'последний', translation: 'last', learned: false },
  { translatedWord: 'только', translation: 'only', learned: false },
  { translatedWord: 'после', translation: 'after', learned: false },
  { translatedWord: 'сначала', translation: 'at first', learned: false },
  { translatedWord: 'время', translation: 'time', learned: false },
  { translatedWord: 'говорит', translation: 'speaks', learned: false },
  { translatedWord: 'он', translation: 'He', learned: false },
  { translatedWord: 'годы', translation: 'years', learned: false },
  { translatedWord: 'рынок', translation: 'market', learned: false },
  { translatedWord: 'нет', translation: 'no', learned: false },
  { translatedWord: 'над, сверх', translation: 'over', learned: false },
  { translatedWord: 'мы', translation: 'we', learned: false },
  { translatedWord: 'мог', translation: 'could', learned: false },
  { translatedWord: 'если', translation: 'if', learned: false },
  { translatedWord: 'люди', translation: 'people', learned: false },
  { translatedWord: 'процент', translation: 'percent', learned: false },
  { translatedWord: 'такой (он такой козел)', translation: 'such', learned: false },
  { translatedWord: 'Это', translation: 'this is', learned: false },
  { translatedWord: 'больше всего', translation: 'most', learned: false },
  { translatedWord: 'использование', translation: 'use', learned: false },
  { translatedWord: 'потому что', translation: 'because', learned: false },
  { translatedWord: 'любой', translation: 'any', learned: false },
  { translatedWord: 'данные', translation: 'data', learned: false },
  { translatedWord: 'там', translation: 'there', learned: false },
  { translatedWord: 'их (нету их)', translation: 'them', learned: false },
  { translatedWord: 'правительство', translation: 'government', learned: false },
  { translatedWord: 'май', translation: 'may', learned: false },
  { translatedWord: 'программное обеспечение', translation: 'software', learned: false },
  { translatedWord: 'так что', translation: 'so', learned: false },
  { translatedWord: 'Новый', translation: 'New', learned: false },
  { translatedWord: 'теперь', translation: 'now', learned: false },
  { translatedWord: 'многие', translation: 'many', learned: false },
  { translatedWord: 'используемый', translation: 'used', learned: false },
  { translatedWord: 'программа', translation: 'program', learned: false },
  { translatedWord: 'системы', translation: 'systems', learned: false },
  { translatedWord: 'три', translation: 'three', learned: false },
  { translatedWord: 'сделать', translation: 'do', learned: false },
  { translatedWord: 'ооо', translation: 'Inc', learned: false },
  { translatedWord: 'между', translation: 'between', learned: false },
  { translatedWord: 'миллиард', translation: 'billion', learned: false },
  { translatedWord: 'что', translation: 'what', learned: false },
  { translatedWord: 'через', translation: 'through', learned: false },
  { translatedWord: 'в (км в час)', translation: 'per', learned: false },
  { translatedWord: 'сделать', translation: 'make', learned: false },
  { translatedWord: 'прежде', translation: 'before', learned: false },
  { translatedWord: 'должен', translation: 'must', learned: false },
  { translatedWord: 'эти', translation: 'these', learned: false },
  { translatedWord: 'вниз', translation: 'down', learned: false },
  { translatedWord: 'под', translation: 'under', learned: false },
  { translatedWord: 'сделанный', translation: 'made', learned: false },
  { translatedWord: 'Корпорация', translation: 'corporation', learned: false },
  { translatedWord: 'компании', translation: 'companies', learned: false },
  { translatedWord: 'гараздо (гараздо лучше)', translation: 'much', learned: false },
  { translatedWord: 'работа', translation: 'work', learned: false },
  { translatedWord: 'пользователи', translation: 'users', learned: false },
  { translatedWord: 'чиновники', translation: 'officials', learned: false },
  { translatedWord: 'как (робот)', translation: 'like', learned: false },
  { translatedWord: 'бизнес', translation: 'business', learned: false },
  { translatedWord: 'поддержка', translation: 'support', learned: false },
  { translatedWord: 'только (просто)', translation: 'just', learned: false },
  { translatedWord: 'каждый', translation: 'every', learned: false },
  { translatedWord: 'те', translation: 'those', learned: false },
  { translatedWord: 'ее', translation: 'her', learned: false },
  { translatedWord: 'хорошо (2vars)', translation: 'well/good', learned: false },
  { translatedWord: 'с тех пор', translation: 'since', learned: false },
  { translatedWord: 'она', translation: 'she', learned: false },
  { translatedWord: 'информация', translation: 'information', learned: false },
  { translatedWord: 'оба', translation: 'both', learned: false },
  { translatedWord: 'ваш', translation: 'your', learned: false },
  { translatedWord: 'продукты', translation: 'products', learned: false },
  { translatedWord: 'президент', translation: 'president', learned: false },
  { translatedWord: 'доля', translation: 'share', learned: false },
  { translatedWord: 'продажи', translation: 'sales', learned: false },
  { translatedWord: 'где', translation: 'where', learned: false },
  { translatedWord: 'сказать', translation: 'say', learned: false },
  { translatedWord: 'доберитесь', translation: 'get', learned: false },
  { translatedWord: 'сеть', translation: 'network', learned: false },
  { translatedWord: 'против', translation: 'against', learned: false },
  { translatedWord: 'мы', translation: 'We', learned: false },
  { translatedWord: 'в то время как', translation: 'while', learned: false },
  { translatedWord: 'даже', translation: 'even', learned: false },
  { translatedWord: 'если', translation: 'If', learned: false },
  { translatedWord: 'неделя', translation: 'week', learned: false },
  { translatedWord: 'цена', translation: 'price', learned: false },
  { translatedWord: 'группа', translation: 'group', learned: false },
  { translatedWord: 'путь', translation: 'way', learned: false },
  { translatedWord: 'в течение', translation: 'during', learned: false },
  { translatedWord: 'государство', translation: 'state', learned: false },
  { translatedWord: 'все еще', translation: 'still', learned: false },
  { translatedWord: 'то же самое', translation: 'same', learned: false },
  { translatedWord: 'тогда', translation: 'then', learned: false },
  { translatedWord: 'число', translation: 'number', learned: false },
  { translatedWord: 'для', translation: 'For', learned: false },
  { translatedWord: 'они', translation: 'They', learned: false },
  { translatedWord: 'наш', translation: 'our', learned: false },
  { translatedWord: 'очень', translation: 'very', learned: false },
  { translatedWord: 'доли', translation: 'shares', learned: false },
  { translatedWord: 'дальше', translation: 'next', learned: false },
  { translatedWord: 'включая', translation: 'including', learned: false },
  { translatedWord: 'компьютер', translation: 'computer', learned: false },
  { translatedWord: 'набор', translation: 'set', learned: false },
  { translatedWord: 'заявление', translation: 'statement', learned: false },
  { translatedWord: 'доступный', translation: 'available', learned: false },
  { translatedWord: 'как (как ты это сделал?)', translation: 'how', learned: false },
  { translatedWord: 'цены', translation: 'prices', learned: false },
  { translatedWord: 'взять', translation: 'take', learned: false },
  { translatedWord: 'его', translation: 'him', learned: false },
  { translatedWord: 'американский', translation: 'American', learned: false },
  { translatedWord: 'должен', translation: 'must', learned: false },
  { translatedWord: 'часть', translation: 'part', learned: false },
  { translatedWord: 'назад', translation: 'back', learned: false },
  { translatedWord: 'ожидаемый', translation: 'expected', learned: false },
  { translatedWord: 'хороший', translation: 'good', learned: false },
  { translatedWord: 'запас', translation: 'stock', learned: false },
  { translatedWord: 'и', translation: 'And', learned: false },
  { translatedWord: 'высоко', translation: 'high', learned: false },
  { translatedWord: 'другой', translation: 'another', learned: false },
  { translatedWord: 'несколько', translation: 'several', learned: false },
  { translatedWord: 'месяцы', translation: 'months', learned: false },
  { translatedWord: 'конец', translation: 'end', learned: false },
  { translatedWord: 'отчет', translation: 'report', learned: false },
  { translatedWord: 'продукт', translation: 'product', learned: false },
  { translatedWord: 'промышленность', translation: 'industry', learned: false },
  { translatedWord: 'собственный', translation: 'own', learned: false },
  { translatedWord: 'четыре', translation: 'four', learned: false },
  { translatedWord: 'основной', translation: 'major', learned: false },
  { translatedWord: 'потребность', translation: 'need', learned: false },
  { translatedWord: 'власть', translation: 'power', learned: false },
  { translatedWord: 'управление', translation: 'management', learned: false },
  { translatedWord: 'контроль', translation: 'control', learned: false },
  { translatedWord: 'сделал', translation: 'did', learned: false },
  { translatedWord: 'меньше', translation: 'less', learned: false },
  { translatedWord: 'ставка', translation: 'rate', learned: false },
  { translatedWord: 'файл', translation: 'file', learned: false },
  { translatedWord: 'названный', translation: 'called', learned: false },
  { translatedWord: 'Объединенный', translation: 'United', learned: false },
  { translatedWord: 'Как', translation: 'As', learned: false },
  { translatedWord: 'Советский', translation: 'Soviet', learned: false },
  { translatedWord: 'Там', translation: 'There', learned: false },
  { translatedWord: 'секунда', translation: 'second', learned: false },
  { translatedWord: 'без', translation: 'without', learned: false },
  { translatedWord: 'хотеть', translation: 'want', learned: false },
  { translatedWord: 'день', translation: 'day', learned: false },
  { translatedWord: 'найденный', translation: 'found', learned: false },
  { translatedWord: 'месяц', translation: 'month', learned: false },
  { translatedWord: 'сообщенный', translation: 'reported', learned: false },
  { translatedWord: 'развитие', translation: 'development', learned: false },
  { translatedWord: 'помощь', translation: 'help', learned: false },
  { translatedWord: 'цент', translation: 'cent', learned: false },
  { translatedWord: 'публика', translation: 'public', learned: false },
  { translatedWord: 'сегодня', translation: 'today', learned: false },
  { translatedWord: 'Компания (сокращенно)', translation: 'Co', learned: false },
  { translatedWord: 'деньги', translation: 'money', learned: false },
  { translatedWord: 'случай', translation: 'case', learned: false },
  { translatedWord: 'интерес', translation: 'interest', learned: false },
  { translatedWord: 'программы', translation: 'programs', learned: false },
  { translatedWord: 'PC', translation: 'PC', learned: false },
  { translatedWord: 'торговля', translation: 'trading', learned: false },
  { translatedWord: 'базирующийся', translation: 'based', learned: false },
  { translatedWord: 'пять', translation: 'five', learned: false },
  { translatedWord: 'затраты', translation: 'cost', learned: false },
  { translatedWord: 'дни', translation: 'days', learned: false },
  { translatedWord: 'крупный', translation: 'large', learned: false },
  { translatedWord: 'проблемы', translation: 'problems', learned: false },
  { translatedWord: 'также ( я тоже)', translation: 'too', learned: false },
  { translatedWord: 'обслуживание', translation: 'service', learned: false },
  { translatedWord: 'линия', translation: 'line', learned: false },
  { translatedWord: 'пользователь', translation: 'user', learned: false },
  { translatedWord: 'федеральный', translation: 'federal', learned: false },
  { translatedWord: 'немногие', translation: 'few', learned: false },
  { translatedWord: 'в (в школе)', translation: 'At', learned: false },
  { translatedWord: 'включить (не в прямом смысле)', translation: 'include', learned: false },
  { translatedWord: 'сказанный', translation: 'told', learned: false },
  { translatedWord: 'делает', translation: 'does', learned: false },
  { translatedWord: 'движение', translation: 'movement', learned: false },
  { translatedWord: 'план', translation: 'plan', learned: false },
  { translatedWord: 'C', translation: 'with', learned: false },
  { translatedWord: 'технология', translation: 'technology', learned: false },
  { translatedWord: 'увеличение', translation: 'increase', learned: false },
  { translatedWord: 'до', translation: 'until', learned: false },
  { translatedWord: 'производительность', translation: 'performance', learned: false },
  { translatedWord: 'пойти', translation: 'go', learned: false },
  { translatedWord: 'обеспечить', translation: 'ensure', learned: false },
  { translatedWord: 'мог бы', translation: 'could', learned: false },
  { translatedWord: 'результаты', translation: 'results', learned: false },
  { translatedWord: 'предложение', translation: 'offer', learned: false },
  { translatedWord: 'меньше всего', translation: 'least', learned: false },
  { translatedWord: 'управляемый', translation: 'controlled', learned: false },
  { translatedWord: 'маленький', translation: 'small', learned: false },
  { translatedWord: 'действие', translation: 'action', learned: false },
  { translatedWord: 'поток', translation: 'flow', learned: false },
  { translatedWord: 'Windows', translation: 'Windows', learned: false },
  { translatedWord: 'Буш', translation: 'Bush', learned: false },
  { translatedWord: 'Национальный', translation: 'National', learned: false },
  { translatedWord: 'полиция', translation: 'police', learned: false },
  { translatedWord: 'отличный', translation: 'great', learned: false },
  { translatedWord: 'четверть', translation: 'quarter', learned: false },
  { translatedWord: 'мой', translation: 'my', learned: false },
  { translatedWord: 'память', translation: 'memory', learned: false },
  { translatedWord: 'соответственно', translation: 'according', learned: false },
  { translatedWord: 'планы', translation: 'plans', learned: false },
  { translatedWord: 'долго', translation: 'long', learned: false },
  { translatedWord: 'назад', translation: 'back', learned: false },
  { translatedWord: 'вокруг', translation: 'around', learned: false },
  { translatedWord: 'версия', translation: 'version', learned: false },
  { translatedWord: 'диск', translation: 'disk', learned: false },
  { translatedWord: 'повысился', translation: 'rose', learned: false },
  { translatedWord: 'В пятницу', translation: 'on Friday', learned: false },
  { translatedWord: 'рано', translation: 'early', learned: false },
  { translatedWord: 'проблема', translation: 'problem', learned: false },
  { translatedWord: 'думать', translation: 'think', learned: false },
  { translatedWord: 'Президент', translation: 'President', learned: false },
  { translatedWord: 'процесс', translation: 'process', learned: false },
  { translatedWord: 'Один', translation: 'One', learned: false },
  { translatedWord: 'услуги', translation: 'services', learned: false },
  { translatedWord: 'нефть', translation: 'oil', learned: false },
  { translatedWord: 'дом', translation: 'home', learned: false },
  { translatedWord: 'область', translation: 'area', learned: false },
  { translatedWord: 'выше', translation: 'above', learned: false },
  { translatedWord: 'Г. (господин)', translation: 'Mr', learned: false },
  { translatedWord: 'прежний', translation: 'former', learned: false },
  { translatedWord: 'В понедельник', translation: 'on Monday', learned: false },
  { translatedWord: 'однако', translation: 'however', learned: false },
  { translatedWord: 'среди', translation: 'among', learned: false },
  { translatedWord: 'представитель', translation: 'spokesman', learned: false },
  { translatedWord: 'правление', translation: 'board', learned: false },
  { translatedWord: 'уже', translation: 'already', learned: false },
  { translatedWord: 'ранее', translation: 'earlier', learned: false },
  { translatedWord: 'объявленный', translation: 'announced', learned: false },
  { translatedWord: 'стандарт', translation: 'standard', learned: false },
  { translatedWord: 'проблема (спорный вопрос)', translation: 'issue', learned: false },
  { translatedWord: 'нормы', translation: 'rates', learned: false },
  { translatedWord: 'Во вторник', translation: 'on Tuesday', learned: false },
  { translatedWord: 'приложение', translation: 'application', learned: false },
  { translatedWord: 'в пределах', translation: 'within', learned: false },
  { translatedWord: 'немного', translation: 'little', learned: false },
  { translatedWord: 'экономический', translation: 'economic', learned: false },
  { translatedWord: 'Когда', translation: 'When', learned: false },
  { translatedWord: 'члены', translation: 'members', learned: false },
  { translatedWord: 'офис', translation: 'office', learned: false },
  { translatedWord: 'файлы', translation: 'files', learned: false },
  { translatedWord: 'недавний', translation: 'recent', learned: false },
  { translatedWord: 'Государства', translation: 'States', learned: false },
  { translatedWord: 'позже', translation: 'later', learned: false },
  { translatedWord: 'В среду', translation: 'On Wednesday', learned: false },
  { translatedWord: 'лучше', translation: 'better', learned: false },
  { translatedWord: 'Запад', translation: 'West', learned: false },
  { translatedWord: 'мимо', translation: 'past', learned: false },
  { translatedWord: 'На', translation: 'On', learned: false },
  { translatedWord: 'показ', translation: 'show', learned: false },
  { translatedWord: 'приехать', translation: 'come', learned: false },
  { translatedWord: 'руководитель', translation: 'chief', learned: false },
  { translatedWord: 'ли', translation: 'whether', learned: false },
  { translatedWord: 'Это', translation: 'That', learned: false },
  { translatedWord: 'плата', translation: 'pay', learned: false },
  { translatedWord: 'изменение', translation: 'change', learned: false },
  { translatedWord: 'знать', translation: 'know', learned: false },
  { translatedWord: 'единица', translation: 'unit', learned: false },
  { translatedWord: 'шесть', translation: 'six', learned: false },
  { translatedWord: 'положить', translation: 'put', learned: false },
  { translatedWord: 'соглашение', translation: 'agreement', learned: false },
  { translatedWord: 'центы', translation: 'cents', learned: false },
  { translatedWord: 'Некоторые', translation: 'Some', learned: false },
  { translatedWord: 'пример', translation: 'example', learned: false },
  { translatedWord: 'Отдел', translation: 'Department', learned: false },
  { translatedWord: 'В четверг', translation: 'on Thursday', learned: false },
  { translatedWord: 'Фунты', translation: 'Pounds', learned: false },
  { translatedWord: 'жесткий', translation: 'hard', learned: false },
  { translatedWord: 'добавленный', translation: 'added', learned: false },
  { translatedWord: 'Дом', translation: 'House', learned: false },
  { translatedWord: 'местный', translation: 'local', learned: false },
  { translatedWord: 'компания', translation: 'company', learned: false },
  { translatedWord: 'закон', translation: 'law', learned: false },
  { translatedWord: 'мир', translation: 'world', learned: false },
  { translatedWord: 'право', translation: 'right', learned: false },
  { translatedWord: 'производство', translation: 'production', learned: false },
  { translatedWord: 'Вы', translation: 'You', learned: false },
  { translatedWord: 'ценность', translation: 'value', learned: false },
  { translatedWord: 'заказ', translation: 'order', learned: false },
  { translatedWord: 'торговля', translation: 'trade', learned: false },
  { translatedWord: 'финансовый', translation: 'financial', learned: false },
  { translatedWord: 'возможный', translation: 'possible', learned: false },
  { translatedWord: 'далеко', translation: 'far', learned: false },
  { translatedWord: 'доступ', translation: 'access', learned: false },
  { translatedWord: 'проект', translation: 'project', learned: false },
  { translatedWord: 'пункт', translation: 'point', learned: false },
  { translatedWord: 'Однако', translation: 'However', learned: false },
  { translatedWord: 'политический', translation: 'political', learned: false },
  { translatedWord: 'становится', translation: 'become', learned: false },
  { translatedWord: 'особенности', translation: 'features', learned: false },
  { translatedWord: 'упал', translation: 'fell', learned: false },
  { translatedWord: 'поздно', translation: 'late', learned: false },
  { translatedWord: 'новости', translation: 'news', learned: false },
  { translatedWord: 'важный', translation: 'important', learned: false },
  { translatedWord: 'Системы', translation: 'Systems', learned: false },
  { translatedWord: 'движение', translation: 'movement', learned: false },
  { translatedWord: 'директор', translation: 'director', learned: false },
  { translatedWord: 'вооруженные силы', translation: 'armed forces', learned: false },
  { translatedWord: 'общее количество', translation: 'total', learned: false },
  { translatedWord: 'суд', translation: 'court', learned: false },
  { translatedWord: 'здесь', translation: 'here', learned: false },
  { translatedWord: 'иностранный', translation: 'foreign', learned: false },
  { translatedWord: 'начался', translation: 'began', learned: false },
  { translatedWord: 'операции', translation: 'operations', learned: false },
  { translatedWord: 'будущее', translation: 'future', learned: false },
  { translatedWord: 'лучше всего', translation: 'best', learned: false },
  { translatedWord: 'среднее число', translation: 'average', learned: false },
  { translatedWord: 'рост (процесс)', translation: 'growth', learned: false },
  { translatedWord: 'налог', translation: 'tax', learned: false },
  { translatedWord: 'ниже', translation: 'lower', learned: false },
  { translatedWord: 'встреча', translation: 'meeting', learned: false },
  { translatedWord: 'отсавил', translation: 'left', learned: false },
  { translatedWord: 'двигатель', translation: 'engine', learned: false },
  { translatedWord: 'проблемы', translation: 'problems', learned: false },
  { translatedWord: 'дать', translation: 'give', learned: false },
  { translatedWord: 'нас', translation: 'us', learned: false },
  { translatedWord: 'страна', translation: 'country', learned: false },
  { translatedWord: 'чиновник', translation: 'official', learned: false },
  { translatedWord: 'большой', translation: 'big', learned: false },
  { translatedWord: 'проводиться (удерживается)', translation: 'held', learned: false },
  { translatedWord: 'испольнительный', translation: 'executive', learned: false },
  { translatedWord: 'уровень', translation: 'level', learned: false },
  { translatedWord: 'генерал', translation: 'general', learned: false },
  { translatedWord: 'инвестиции', translation: 'investments', learned: false },
  { translatedWord: 'прибыть', translation: 'arrive', learned: false },
  { translatedWord: 'не сделал', translation: 'didn’t do', learned: false },
  { translatedWord: 'председатель', translation: 'chairman', learned: false },
  { translatedWord: 'США', translation: 'USA', learned: false },
  { translatedWord: 'найти', translation: 'find', learned: false },
  { translatedWord: 'я', translation: 'I', learned: false },
  { translatedWord: 'близко', translation: 'close', learned: false },
  { translatedWord: 'Июнь', translation: 'June', learned: false },
  { translatedWord: 'диапазон', translation: 'range', learned: false },
  { translatedWord: 'данный', translation: 'given', learned: false },
  { translatedWord: 'интерфейс', translation: 'interface', learned: false },
  { translatedWord: 'купить', translation: 'buy', learned: false },
  { translatedWord: 'К', translation: 'To', learned: false },
  { translatedWord: 'Японский язык', translation: 'Japanese', learned: false },
  { translatedWord: 'реальный', translation: 'real', learned: false },
  { translatedWord: 'взял', translation: 'took', learned: false },
  { translatedWord: 'место', translation: 'place', learned: false },
  { translatedWord: 'банк', translation: 'bank', learned: false },
  { translatedWord: 'создание (процесс)', translation: 'making', learned: false },
  { translatedWord: 'включает', translation: 'includes', learned: false },
  { translatedWord: 'результат', translation: 'result', learned: false },
  { translatedWord: 'фирма', translation: 'firm', learned: false },
  { translatedWord: 'С', translation: 'With', learned: false },
  { translatedWord: 'база данных', translation: 'database', learned: false },
  { translatedWord: 'модель', translation: 'model', learned: false },
  { translatedWord: 'сообщения', translation: 'messages', learned: false },
  { translatedWord: 'половина', translation: 'half', learned: false },
  { translatedWord: 'каждый', translation: 'every', learned: false },
  { translatedWord: 'пункты', translation: 'points', learned: false },
  { translatedWord: 'Март', translation: 'March', learned: false },
  { translatedWord: 'никогда', translation: 'never', learned: false },
  { translatedWord: 'достаточно', translation: 'enough', learned: false },
  { translatedWord: 'обеспечивает', translation: 'provides', learned: false },
  { translatedWord: 'вчера', translation: 'yesterday', learned: false },
  { translatedWord: 'времена', translation: 'times', learned: false },
  { translatedWord: 'дополнение', translation: 'addition', learned: false },
  { translatedWord: 'Нет', translation: 'No', learned: false },
  { translatedWord: 'жизнь', translation: 'life', learned: false },
  { translatedWord: 'обычный', translation: 'ordinary', learned: false },
  { translatedWord: 'изменения', translation: 'changes', learned: false },
  { translatedWord: 'не делает', translation: 'doesn’t do', learned: false },
  { translatedWord: 'далее', translation: 'further', learned: false },
  { translatedWord: 'вершина', translation: 'top', learned: false },
  { translatedWord: 'решение', translation: 'decision', learned: false },
  { translatedWord: 'сравнивать', translation: 'compare', learned: false },
  { translatedWord: 'вероятно', translation: 'likely', learned: false },
  { translatedWord: 'должный', translation: 'due', learned: false },
  { translatedWord: 'период', translation: 'period', learned: false },
  { translatedWord: 'открытый', translation: 'open', learned: false },
  { translatedWord: 'рынки', translation: 'markets', learned: false },
  { translatedWord: 'звонить', translation: 'call', learned: false },
  { translatedWord: 'капитал', translation: 'capital', learned: false },
  { translatedWord: 'название', translation: 'name', learned: false },
  { translatedWord: 'национальный', translation: 'national', learned: false },
  { translatedWord: 'закрытый', translation: 'closed', learned: false },
  { translatedWord: 'недавно', translation: 'recently', learned: false },
  { translatedWord: 'предложенный', translation: 'proposed', learned: false },
  { translatedWord: 'единственный', translation: 'single', learned: false },
  { translatedWord: 'способный', translation: 'able', learned: false },
  { translatedWord: 'партия', translation: 'party', learned: false },
  { translatedWord: 'проданный', translation: 'sold', learned: false },
  { translatedWord: 'Юг', translation: 'South', learned: false },
  { translatedWord: 'пакет', translation: 'package', learned: false },
  { translatedWord: 'тест', translation: 'test', learned: false },
  { translatedWord: 'клиенты (2ой перевод)', translation: 'customers', learned: false },
  { translatedWord: 'Британский', translation: 'British', learned: false },
  { translatedWord: 'сокращение', translation: 'reduction', learned: false },
  { translatedWord: 'продавать', translation: 'sell', learned: false },
  { translatedWord: 'Международный', translation: 'International', learned: false },
  { translatedWord: 'полный', translation: 'full', learned: false },
  { translatedWord: 'контроль, управление', translation: 'control', learned: false },
  { translatedWord: 'оборудование', translation: 'equipment', learned: false },
  { translatedWord: 'компьютеры', translation: 'computers', learned: false },
  { translatedWord: 'индекс', translation: 'index', learned: false },
  { translatedWord: 'Конгресс', translation: 'Congress', learned: false },
  { translatedWord: 'контракт', translation: 'contract', learned: false },
  { translatedWord: 'бумага', translation: 'paper', learned: false },
  { translatedWord: 'рабочие', translation: 'workers', learned: false },
  { translatedWord: 'недостаток', translation: 'lack', learned: false },
  { translatedWord: 'исследование', translation: 'study', learned: false },
  { translatedWord: 'другие', translation: 'other', learned: false },
  { translatedWord: 'Система', translation: 'System', learned: false },
  { translatedWord: 'исследование', translation: 'research', learned: false },
  { translatedWord: 'низко', translation: 'low', learned: false },
  { translatedWord: 'делает', translation: 'makes', learned: false },
  { translatedWord: 'Федеральный', translation: 'Federal', learned: false },
  { translatedWord: 'город', translation: 'city', learned: false },
  { translatedWord: 'Май', translation: 'May', learned: false },
  { translatedWord: 'добрался', translation: 'got', learned: false },
  { translatedWord: 'семья', translation: 'family', learned: false },
  { translatedWord: 'политика', translation: 'politics', learned: false },
  { translatedWord: 'инвесторы', translation: 'investors', learned: false },
  { translatedWord: 'потеря', translation: 'loss', learned: false },
  { translatedWord: 'полученный', translation: 'received', learned: false },
  { translatedWord: 'Апрель', translation: 'April', learned: false },
  { translatedWord: 'Обмен', translation: 'Exchange', learned: false },
  { translatedWord: 'кодекс', translation: 'code', learned: false },
  { translatedWord: 'графика', translation: 'graphics', learned: false },
  { translatedWord: 'агентство', translation: 'agency', learned: false },
  { translatedWord: 'увеличенный', translation: 'increased', learned: false },
  { translatedWord: 'менеджер', translation: 'manager', learned: false },
  { translatedWord: 'держать', translation: 'keep', learned: false },
  { translatedWord: 'смотреть', translation: 'look', learned: false },
  { translatedWord: 'часто', translation: 'often', learned: false },
  { translatedWord: 'разработанный', translation: 'developed', learned: false },
  { translatedWord: 'Европеец', translation: 'European', learned: false },
  { translatedWord: 'окружающая среда', translation: 'environment', learned: false },
  { translatedWord: 'Июль', translation: 'July', learned: false },
  { translatedWord: 'работа', translation: 'job', learned: false },
  { translatedWord: 'треть', translation: 'third', learned: false },
  { translatedWord: 'вода', translation: 'water', learned: false },
  { translatedWord: 'сеть', translation: 'network', learned: false },
  { translatedWord: 'банки', translation: 'banks', learned: false },
  { translatedWord: 'аналитики', translation: 'analysts', learned: false },
  { translatedWord: 'сильный', translation: 'strong', learned: false },
  { translatedWord: 'сторона', translation: 'side', learned: false },
  { translatedWord: 'экономика', translation: 'economy', learned: false },
  { translatedWord: 'далеко', translation: 'far', learned: false },
  { translatedWord: 'доллар', translation: 'dollar', learned: false },
  { translatedWord: 'взятый', translation: 'taken', learned: false },
  { translatedWord: 'развитый', translation: 'developed', learned: false },
  { translatedWord: 'продолжить', translation: 'continue', learned: false },
  { translatedWord: 'позволить', translation: 'allow', learned: false },
  { translatedWord: 'ключ', translation: 'key', learned: false },
  { translatedWord: 'также', translation: 'also', learned: false },
  { translatedWord: 'безопасность', translation: 'safety', learned: false },
  { translatedWord: 'проект', translation: 'project', learned: false },
  { translatedWord: 'согласованный', translation: 'agreed', learned: false },
  { translatedWord: 'хотя', translation: 'although', learned: false },
  { translatedWord: 'Япония', translation: 'Japan', learned: false },
  { translatedWord: 'скорее', translation: 'rather', learned: false },
  { translatedWord: 'страны', translation: 'countries', learned: false },
  { translatedWord: 'завод (2ой перевод)', translation: 'plant', learned: false },
  { translatedWord: 'вперед', translation: 'forward', learned: false },
  { translatedWord: 'Яблоко', translation: 'Apple', learned: false },
  { translatedWord: 'действие', translation: 'action', learned: false },
  { translatedWord: 'После', translation: 'After', learned: false },
  { translatedWord: 'экран', translation: 'screen', learned: false },
  { translatedWord: 'война', translation: 'war', learned: false },
  { translatedWord: 'обработка', translation: 'processing', learned: false },
  { translatedWord: 'служащие', translation: 'employees', learned: false },
  { translatedWord: 'включенный', translation: 'included', learned: false },
  { translatedWord: 'спрошенный', translation: 'asked', learned: false },
  { translatedWord: 'особенный', translation: 'special', learned: false },
  { translatedWord: 'область, поле', translation: 'field', learned: false },
  { translatedWord: 'энергия', translation: 'energy', learned: false },
  { translatedWord: 'старый', translation: 'old', learned: false },
  { translatedWord: 'дело', translation: 'deal', learned: false },
  { translatedWord: 'предложения', translation: 'offers', learned: false },
  { translatedWord: 'почти (2ой перевод)', translation: 'nearly', learned: false },
  { translatedWord: 'недели', translation: 'weeks', learned: false },
  { translatedWord: 'долг', translation: 'debt', learned: false },
  { translatedWord: 'Она', translation: 'She', learned: false },
  { translatedWord: 'обвинения', translation: 'charges', learned: false },
  { translatedWord: 'Союз', translation: 'Union', learned: false },
  { translatedWord: 'потребности', translation: 'needs', learned: false },
  { translatedWord: 'эффект', translation: 'effect', learned: false },
  { translatedWord: 'доход', translation: 'income', learned: false },
  { translatedWord: 'использование', translation: 'usage', learned: false },
  { translatedWord: 'снова', translation: 'again', learned: false },
  { translatedWord: 'Компьютер', translation: 'Computer', learned: false },
  { translatedWord: 'Восток', translation: 'East', learned: false },
  { translatedWord: 'подобный', translation: 'similar', learned: false },
  { translatedWord: 'Европа', translation: 'Europe', learned: false },
  { translatedWord: 'рядом', translation: 'near', learned: false },
  { translatedWord: 'создать', translation: 'create', learned: false },
  { translatedWord: 'форма', translation: 'form', learned: false },
  { translatedWord: 'главный', translation: 'main', learned: false },
  { translatedWord: 'свободный', translation: 'free', learned: false },
  { translatedWord: 'наибольший', translation: 'largest', learned: false },
  { translatedWord: 'возвратитесь', translation: 'return', learned: false },
  { translatedWord: 'машина', translation: 'machine', learned: false },
  { translatedWord: 'часы', translation: 'clock', learned: false },
  { translatedWord: 'до сих пор', translation: 'yet', learned: false },
  { translatedWord: 'текст', translation: 'text', learned: false },
  { translatedWord: 'почти', translation: 'almost', learned: false },
  { translatedWord: 'Все', translation: 'All', learned: false },
  { translatedWord: 'человек', translation: 'human', learned: false },
  { translatedWord: 'необходимый (2 варианта)', translation: 'required/necessary', learned: false },
  { translatedWord: 'аппаратура', translation: 'hardware', learned: false },
  { translatedWord: 'частный', translation: 'private', learned: false },
  { translatedWord: 'позволяет', translation: 'allows', learned: false },
  { translatedWord: 'убитый', translation: 'killed', learned: false },
  { translatedWord: 'международный', translation: 'international', learned: false },
  { translatedWord: 'известный', translation: 'famous', learned: false },
  { translatedWord: 'вещи', translation: 'things', learned: false },
  { translatedWord: 'основа', translation: 'base', learned: false },
  { translatedWord: 'облигации', translation: 'bonds', learned: false },
  { translatedWord: 'группы', translation: 'groups', learned: false },
  { translatedWord: 'список', translation: 'list', learned: false },
  { translatedWord: 'сделанный (2 var)', translation: 'done/made', learned: false },
  { translatedWord: 'средства', translation: 'funds', learned: false },
  { translatedWord: 'дополнительный', translation: 'additional', learned: false },
  { translatedWord: 'газ', translation: 'gas', learned: false },
  { translatedWord: 'области', translation: 'areas', learned: false },
  { translatedWord: 'попытка', translation: 'attempt', learned: false },
  { translatedWord: 'сила', translation: 'force', learned: false },
  { translatedWord: 'капитал', translation: 'capital', learned: false },
  { translatedWord: 'потерянный', translation: 'lost', learned: false },
  { translatedWord: 'однажды', translation: 'once', learned: false },
  { translatedWord: 'не может', translation: 'cant', learned: false },
  { translatedWord: 'сервер', translation: 'server', learned: false },
  { translatedWord: 'Город', translation: 'City', learned: false },
  { translatedWord: 'запросы', translation: 'requests', learned: false },
  { translatedWord: 'пространство', translation: 'space', learned: false },
  { translatedWord: 'ежегодный', translation: 'annual', learned: false },
  { translatedWord: 'цвет', translation: 'color', learned: false },
  { translatedWord: 'В воскресенье', translation: 'on Sunday', learned: false },
  { translatedWord: 'сети', translation: 'networks', learned: false },
  { translatedWord: 'верить', translation: 'believe', learned: false },
  { translatedWord: 'размер', translation: 'size', learned: false },
  { translatedWord: 'администрация', translation: 'administration', learned: false },
  { translatedWord: 'государства', translation: 'states', learned: false },
  { translatedWord: 'функции', translation: 'functions', learned: false },
  { translatedWord: 'выпуск', translation: 'release', learned: false },
  { translatedWord: 'корпоративный', translation: 'corporate', learned: false },
  { translatedWord: 'поперек', translation: 'across', learned: false },
  { translatedWord: 'необходимый', translation: 'required', learned: false },
  { translatedWord: 'мили', translation: 'miles', learned: false },
  { translatedWord: 'комментарий', translation: 'comment', learned: false },
  { translatedWord: 'здание', translation: 'building', learned: false },
  { translatedWord: 'прибывает', translation: 'arrives', learned: false },
  { translatedWord: 'требование', translation: 'demand', learned: false },
  { translatedWord: 'акции (запас)', translation: 'stock', learned: false },
  { translatedWord: 'начало', translation: 'start', learned: false },
  { translatedWord: 'действительно', translation: 'really', learned: false },
  { translatedWord: 'Генерал', translation: 'General', learned: false },
  { translatedWord: 'наличные деньги', translation: 'cash', learned: false },
  { translatedWord: 'кампания', translation: 'campaign', learned: false },
  { translatedWord: 'голова', translation: 'head', learned: false },
  { translatedWord: 'дети', translation: 'children', learned: false },
  { translatedWord: 'пошел', translation: 'went', learned: false },
  { translatedWord: 'вероятно', translation: 'probably', learned: false },
  { translatedWord: 'маркетинг', translation: 'marketing', learned: false },
  { translatedWord: 'счет (к примеру денежный)', translation: 'bill', learned: false },
  { translatedWord: 'ночь', translation: 'night', learned: false },
  { translatedWord: 'В то время как', translation: 'While', learned: false },
  { translatedWord: 'линии', translation: 'lines', learned: false },
  { translatedWord: 'высказывание (2 var)', translation: 'utterance', learned: false },
  { translatedWord: 'прибыль', translation: 'profit', learned: false },
  { translatedWord: 'ряд', translation: 'row', learned: false },
  { translatedWord: 'Государство', translation: 'State', learned: false },
  { translatedWord: 'потенциал', translation: 'potential', learned: false },
  { translatedWord: 'Хотя', translation: 'Although', learned: false },
  { translatedWord: 'инструменты', translation: 'tools', learned: false },
  { translatedWord: 'напечатать (к примеру на клавиатуре)', translation: 'type', learned: false },
  { translatedWord: 'количество', translation: 'amount', learned: false },
  { translatedWord: 'финал', translation: 'final', learned: false },
  { translatedWord: 'продажа', translation: 'sale', learned: false },
  { translatedWord: 'Университет', translation: 'University', learned: false },
  { translatedWord: 'препарат', translation: 'drug', learned: false },
  { translatedWord: 'машины', translation: 'machines', learned: false },
  { translatedWord: 'Север', translation: 'North', learned: false },
  { translatedWord: 'бюджет', translation: 'budget', learned: false },
  { translatedWord: 'анализ', translation: 'analysis', learned: false },
  { translatedWord: 'Госпожа.', translation: 'Ms.', learned: false },
  { translatedWord: 'случаи', translation: 'cases', learned: false },
  { translatedWord: 'автомобиль', translation: 'car', learned: false },
  { translatedWord: 'последующий', translation: 'following', learned: false },
  { translatedWord: 'законченный (3 vars)', translation: 'completed/finished/ended', learned: false },
  { translatedWord: 'чей', translation: 'whose', learned: false },
  { translatedWord: 'лидеры', translation: 'leaders', learned: false },
  { translatedWord: 'продавцы', translation: 'vendors', learned: false },
  { translatedWord: 'Больше всего', translation: 'the most', learned: false },
  { translatedWord: 'утверждение', translation: 'statement', learned: false },
  { translatedWord: 'хотя', translation: 'although', learned: false },
  { translatedWord: 'определенный', translation: 'certain', learned: false },
  { translatedWord: 'операция', translation: 'operation', learned: false },
  { translatedWord: 'беспокойство, забота', translation: 'concern', learned: false },
  { translatedWord: 'функция', translation: 'function', learned: false },
  { translatedWord: 'факт', translation: 'fact', learned: false },
  { translatedWord: 'падение', translation: 'fall', learned: false },
  { translatedWord: 'воздух', translation: 'air', learned: false },
  { translatedWord: 'выпущенный', translation: 'released', learned: false },
  { translatedWord: 'Немецкий язык', translation: 'German', learned: false },
  { translatedWord: 'непосредственно', translation: 'directly', learned: false },
  { translatedWord: 'обмен', translation: 'exchange', learned: false },
  { translatedWord: 'персонал', translation: 'staff', learned: false },
  { translatedWord: 'кое-что', translation: 'something', learned: false },
  { translatedWord: 'телефон', translation: 'phone', learned: false },
  { translatedWord: 'школа', translation: 'school', learned: false },
  { translatedWord: 'положение', translation: 'position', learned: false },
  { translatedWord: 'предыдущий', translation: 'previous', learned: false },
  { translatedWord: 'предложение, заявка', translation: 'proposal', learned: false },
  { translatedWord: 'не будет', translation: 'wont', learned: false },
  { translatedWord: 'Запас', translation: 'Stock', learned: false },
  { translatedWord: 'снаружи', translation: 'outside', learned: false },
  { translatedWord: 'Группа', translation: 'Group', learned: false },
  { translatedWord: 'права', translation: 'rights', learned: false },
  { translatedWord: 'уровни', translation: 'levels', learned: false },
  { translatedWord: 'Так', translation: 'So', learned: false },
  { translatedWord: 'вовлеченный', translation: 'involved', learned: false },
  { translatedWord: 'всегда', translation: 'always', learned: false },
  { translatedWord: 'отображение', translation: 'display', learned: false },
  { translatedWord: 'источник', translation: 'source', learned: false },
  { translatedWord: 'метод', translation: 'method', learned: false },
  { translatedWord: 'лидер', translation: 'leader', learned: false },
  { translatedWord: 'язык', translation: 'language', learned: false },
  { translatedWord: 'переговоры (2 vars)', translation: 'converstation/discussion', learned: false },
  { translatedWord: 'сроки', translation: 'terms', learned: false },
  { translatedWord: 'качество', translation: 'quality', learned: false },
  { translatedWord: 'Многие', translation: 'Many', learned: false },
  { translatedWord: 'коммуникации', translation: 'communications', learned: false },
  { translatedWord: 'должносное лицо', translation: 'official', learned: false },
  { translatedWord: 'предполагаемый', translation: 'supposed', learned: false },
  { translatedWord: 'ведомый', translation: 'led', learned: false },
  { translatedWord: 'обвинение', translation: 'charge', learned: false },
  { translatedWord: 'черный', translation: 'black', learned: false },
  { translatedWord: 'Германия', translation: 'Germany', learned: false },
  { translatedWord: 'Программное обеспечение', translation: 'Software', learned: false },
  { translatedWord: 'старший', translation: 'senior', learned: false },
  { translatedWord: 'достигнутый', translation: 'reached', learned: false },
  { translatedWord: 'вместе', translation: 'together', learned: false },
  { translatedWord: 'восемь', translation: 'eight', learned: false },
  { translatedWord: 'продажа (процесс)', translation: 'selling', learned: false },
  { translatedWord: 'повышение', translation: 'rise', learned: false },
  { translatedWord: 'Америка', translation: 'America', learned: false },
  { translatedWord: 'трудный', translation: 'difficult', learned: false },
  { translatedWord: 'великий', translation: 'great', learned: false },
  { translatedWord: 'стандарты', translation: 'standards', learned: false },
  { translatedWord: 'принтер', translation: 'printer', learned: false },
  { translatedWord: 'наличие', translation: 'having', learned: false },
  { translatedWord: 'замеченный', translation: 'seen', learned: false },
  { translatedWord: 'различный', translation: 'various', learned: false },
  { translatedWord: 'скорость', translation: 'speed', learned: false },
  { translatedWord: 'продуманный', translation: 'thoughtful', learned: false },
  { translatedWord: 'Сначала', translation: 'at first', learned: false },
  { translatedWord: 'уменьшенный', translation: 'reduced', learned: false },
  { translatedWord: 'последний', translation: 'last', learned: false },
  { translatedWord: 'центральный', translation: 'central', learned: false },
  { translatedWord: 'ядерный', translation: 'nuclear', learned: false },
  { translatedWord: 'в настоящее время', translation: 'currently', learned: false },
  { translatedWord: 'голосование', translation: 'vote', learned: false },
  { translatedWord: 'существующий', translation: 'existing', learned: false },
  { translatedWord: 'выше', translation: 'above', learned: false },
  { translatedWord: 'Его (одежда)', translation: 'His', learned: false },
  { translatedWord: 'коммерческий', translation: 'commercial', learned: false },
  { translatedWord: 'ясный', translation: 'clear', learned: false },
  { translatedWord: 'студенты', translation: 'students', learned: false },
  { translatedWord: 'Суд', translation: 'Court', learned: false },
  { translatedWord: 'Обслуживание', translation: 'Service', learned: false },
  { translatedWord: 'доход (2 vars)', translation: 'income/profit', learned: false },
  { translatedWord: 'В субботу', translation: 'on Saturday', learned: false },
  { translatedWord: 'давление', translation: 'pressure', learned: false },
  { translatedWord: 'усилие', translation: 'effort', learned: false },
  { translatedWord: 'взятие', translation: 'taking', learned: false },
  { translatedWord: 'если', translation: 'if', learned: false },
  { translatedWord: 'подарок', translation: 'present', learned: false },
  { translatedWord: 'встретьтесь', translation: 'meet', learned: false },
  { translatedWord: 'условия', translation: 'conditions', learned: false },
  { translatedWord: 'подход', translation: 'approach', learned: false },
  { translatedWord: 'продукция', translation: 'products', learned: false },
  { translatedWord: 'предложение', translation: 'proposition', learned: false },
  { translatedWord: 'штат', translation: 'state', learned: false },
  { translatedWord: 'смерть', translation: 'death', learned: false },
  { translatedWord: 'описанный', translation: 'described', learned: false },
  { translatedWord: 'слово', translation: 'word', learned: false },
  { translatedWord: 'женщины', translation: 'women', learned: false },
  { translatedWord: 'прибыль', translation: 'profit', learned: false },
  { translatedWord: 'источники', translation: 'sources', learned: false },
  { translatedWord: 'легкий (степень сложности)', translation: 'easy', learned: false },
  { translatedWord: 'расходы', translation: 'costs', learned: false },
  { translatedWord: 'Январь', translation: 'January', learned: false },
  { translatedWord: 'видео', translation: 'video', learned: false },
  { translatedWord: 'мужчины', translation: 'men', learned: false },
  { translatedWord: 'роль', translation: 'role', learned: false },
  { translatedWord: 'технический', translation: 'technical', learned: false },
  { translatedWord: 'умерший', translation: 'died', learned: false },
  { translatedWord: 'семь', translation: 'seven', learned: false },
  { translatedWord: 'изображение', translation: 'image', learned: false },
  { translatedWord: 'курс', translation: 'course', learned: false },
  { translatedWord: 'Госпожа.', translation: 'Mrs.', learned: false },
  { translatedWord: 'конференция', translation: 'conference', learned: false },
  { translatedWord: 'телевидение', translation: 'television', learned: false },
  { translatedWord: 'предлагаемый', translation: 'proposed', learned: false },
  { translatedWord: 'существенный', translation: 'significant', learned: false },
  { translatedWord: 'посланный', translation: 'sent', learned: false },
  { translatedWord: 'оставаться', translation: 'remain', learned: false },
  { translatedWord: 'правило', translation: 'rule', learned: false },
  { translatedWord: 'Данные', translation: 'Data', learned: false },
  { translatedWord: 'заплаченный', translation: 'paid', learned: false },
  { translatedWord: 'запланированный', translation: 'planned', learned: false },
  { translatedWord: 'Декабрь', translation: 'December', learned: false },
  { translatedWord: 'способность', translation: 'ability', learned: false },
  { translatedWord: 'менеджеры', translation: 'managers', learned: false },
  { translatedWord: 'Улица', translation: 'Street', learned: false },
  { translatedWord: 'Оба', translation: 'Both', learned: false },
  { translatedWord: 'основание', translation: 'base', learned: false },
  { translatedWord: 'единицы', translation: 'units', learned: false },
  { translatedWord: 'сторона', translation: 'side', learned: false },
  { translatedWord: 'представление', translation: 'xxx', learned: false },
  { translatedWord: 'ценные бумаги', translation: 'securities', learned: false },
  { translatedWord: 'полный', translation: 'full', learned: false },
  { translatedWord: 'пища', translation: 'food', learned: false },
  { translatedWord: 'лидерство', translation: 'leadership', learned: false },
  { translatedWord: 'активы', translation: 'assets', learned: false },
  { translatedWord: 'карточка', translation: 'card', learned: false },
  { translatedWord: 'короткий', translation: 'short', learned: false },
  { translatedWord: 'Что', translation: 'What', learned: false },
  { translatedWord: 'кредит', translation: 'credit', learned: false },
  { translatedWord: 'выполнение', translation: 'execution', learned: false },
  { translatedWord: 'Мир', translation: 'World', learned: false },
  { translatedWord: 'Воздух', translation: 'Air', learned: false },
  { translatedWord: 'силы', translation: 'forces', learned: false },
  { translatedWord: 'Сентябрь', translation: 'September', learned: false },
  { translatedWord: 'части', translation: 'parts', learned: false },
  { translatedWord: 'лицо', translation: 'face', learned: false },
  { translatedWord: 'вопрос', translation: 'question', learned: false },
  { translatedWord: 'уменьшить', translation: 'reduce', learned: false },
  { translatedWord: 'Теперь', translation: 'Now', learned: false },
  { translatedWord: 'требования', translation: 'requirements', learned: false },
  { translatedWord: 'защита', translation: 'defense', learned: false },
  { translatedWord: 'огонь', translation: 'fire', learned: false },
  { translatedWord: 'дата', translation: 'date', learned: false },
  { translatedWord: 'Белый', translation: 'White', learned: false },
  { translatedWord: 'усилия', translation: 'efforts', learned: false },
  { translatedWord: 'структура', translation: 'structure', learned: false },
  { translatedWord: 'определенный', translation: 'certain', learned: false },
  { translatedWord: 'требовать', translation: 'demand', learned: false },
  { translatedWord: 'скоро', translation: 'soon', learned: false },
  { translatedWord: 'обзор', translation: 'review', learned: false },
  { translatedWord: 'Октябрь', translation: 'October', learned: false },
  { translatedWord: 'к', translation: 'to', learned: false },
  { translatedWord: 'ожидать', translation: 'expect', learned: false },
  { translatedWord: 'фигуры', translation: 'figures', learned: false },
  { translatedWord: 'простой', translation: 'simple', learned: false },
  { translatedWord: 'член', translation: 'member', learned: false },
  { translatedWord: 'Доллары', translation: 'Dollars', learned: false },
  { translatedWord: 'взгляд', translation: 'view', learned: false },
  { translatedWord: 'рабочие места', translation: 'workplaces', learned: false },
  { translatedWord: 'здоровье', translation: 'health', learned: false },
  { translatedWord: 'правила', translation: 'rules', learned: false },
  { translatedWord: 'работы', translation: 'works', learned: false },
  { translatedWord: 'держитесь', translation: 'hold', learned: false },
  { translatedWord: 'дал', translation: 'gave', learned: false },
  { translatedWord: 'необходимый', translation: 'necessary', learned: false },
  { translatedWord: 'получение', translation: 'receiving', learned: false },
  { translatedWord: 'ограниченный', translation: 'limited', learned: false },
  { translatedWord: 'показал', translation: 'showed', learned: false },
  { translatedWord: 'показы', translation: 'shows', learned: false },
  { translatedWord: 'названный', translation: 'named', learned: false },
  { translatedWord: 'вещь', translation: 'thing', learned: false },
  { translatedWord: 'способности', translation: 'capabilities', learned: false },
  { translatedWord: 'Другой', translation: 'another', learned: false },
  { translatedWord: 'представленный', translation: 'represented', learned: false },
  { translatedWord: 'особенно', translation: 'especially', learned: false },
  { translatedWord: 'когда-либо', translation: 'ever', learned: false },
  { translatedWord: 'комитет', translation: 'committee', learned: false },
  { translatedWord: 'ответ, отклик', translation: 'response', learned: false },
  { translatedWord: 'поддержкa', translation: 'support', learned: false },
  { translatedWord: 'процессор', translation: 'processor', learned: false },
  { translatedWord: 'поворот', translation: 'turn', learned: false },
  { translatedWord: 'объем', translation: 'volume', learned: false },
  { translatedWord: 'оцененный', translation: 'priced', learned: false },
  { translatedWord: 'обязательство', translation: 'obligation', learned: false },
  { translatedWord: 'модели', translation: 'models', learned: false },
  { translatedWord: 'страхование', translation: 'insurance', learned: false },
  { translatedWord: 'Комиссия', translation: 'commission', learned: false },
  { translatedWord: 'требует', translation: 'requires', learned: false },
  { translatedWord: 'выигранный', translation: 'won', learned: false },
  { translatedWord: 'многократный', translation: 'multiple', learned: false },
  { translatedWord: 'отдельный', translation: 'separate', learned: false },
  { translatedWord: 'начатый', translation: 'started', learned: false },
  { translatedWord: 'Правление', translation: 'government', learned: false },
  { translatedWord: 'С тех пор', translation: 'Since', learned: false },
  { translatedWord: 'через (2 vars)', translation: 'via/through', learned: false },
  { translatedWord: 'книга', translation: 'book', learned: false },
  { translatedWord: 'варианты', translation: 'options', learned: false },
  { translatedWord: 'поставка', translation: 'supply', learned: false },
  { translatedWord: 'войска', translation: 'troops', learned: false },
  { translatedWord: 'Два', translation: 'Two', learned: false },
  { translatedWord: 'решительный', translation: 'determined', learned: false },
  { translatedWord: 'созданный', translation: 'created', learned: false },
  { translatedWord: 'длительный', translation: 'long', learned: false },
  { translatedWord: 'тесты', translation: 'tests', learned: false },
  { translatedWord: 'позволить (2 vars)', translation: 'allow/let', learned: false },
  { translatedWord: 'начать', translation: 'begin', learned: false },
  { translatedWord: 'стал', translation: 'became', learned: false },
  { translatedWord: 'дольше', translation: 'longer', learned: false },
  { translatedWord: 'хит', translation: 'hit', learned: false },
  { translatedWord: 'дом', translation: 'house', learned: false },
  { translatedWord: 'потери', translation: 'losses', learned: false },
  { translatedWord: 'продвижение, содействие', translation: 'promotion', learned: false },
  { translatedWord: 'Август', translation: 'August', learned: false },
  { translatedWord: 'закупка', translation: 'purchase', learned: false },
  { translatedWord: 'команда', translation: 'team', learned: false },
  { translatedWord: 'непосредственно', translation: 'directly', learned: false },
  { translatedWord: 'национальный', translation: 'national', learned: false },
  { translatedWord: 'финансовый', translation: 'financial', learned: false },
  { translatedWord: 'развейтесь', translation: 'develop', learned: false },
  { translatedWord: 'мысль', translation: 'thought', learned: false },
  { translatedWord: 'счет', translation: 'account', learned: false },
  { translatedWord: 'комплекс', translation: 'complex', learned: false },
  { translatedWord: 'берет', translation: 'takes', learned: false },
  { translatedWord: 'произвести', translation: 'produce', learned: false },
  { translatedWord: 'пробовать', translation: 'try', learned: false },
  { translatedWord: 'поданный, представленный, подвергнутый ', translation: 'submitted', learned: false },
  { translatedWord: 'Ассоциация', translation: 'Association', learned: false },
  { translatedWord: 'обсужденный', translation: 'discussed', learned: false },
  { translatedWord: 'хочет', translation: 'wants', learned: false },
  { translatedWord: 'документ', translation: 'document', learned: false },
  { translatedWord: 'внизу', translation: 'below', learned: false },
  { translatedWord: 'позади', translation: 'behind', learned: false },
  { translatedWord: 'Даже', translation: 'Even', learned: false },
  { translatedWord: 'показанный', translation: 'shown', learned: false },
  { translatedWord: 'обучение', translation: 'education', learned: false },
  { translatedWord: 'отдел', translation: 'department', learned: false },
  { translatedWord: 'двигатели', translation: 'engines', learned: false },
  { translatedWord: 'фирмы', translation: 'firms', learned: false },
  { translatedWord: 'рост', translation: 'growth', learned: false },
  { translatedWord: 'Последний', translation: 'Last', learned: false },
  { translatedWord: 'аналитик', translation: 'analyst', learned: false },
  { translatedWord: 'команда', translation: 'team', learned: false },
  { translatedWord: 'играть', translation: 'play', learned: false },
  { translatedWord: 'нажать', translation: 'press', learned: false },
  { translatedWord: 'почему', translation: 'why', learned: false },
  { translatedWord: 'программирование', translation: 'programming', learned: false },
  { translatedWord: 'союз', translation: 'union', learned: false },
  { translatedWord: 'испытание', translation: 'trial', learned: false },
  { translatedWord: 'причина', translation: 'reason', learned: false },
  { translatedWord: 'ВЕЛИКОБРИТАНИЯ', translation: 'Great Britain', learned: false },
  { translatedWord: 'вид, тип', translation: 'kind', learned: false },
  { translatedWord: 'особенность', translation: 'feature', learned: false },
  { translatedWord: 'свет', translation: 'light', learned: false },
  { translatedWord: 'Ноябрь', translation: 'November', learned: false },
  { translatedWord: 'Демократичный', translation: 'democratic', learned: false },
  { translatedWord: 'Менеджер', translation: 'Manager', learned: false },
  { translatedWord: 'числа', translation: 'numbers', learned: false },
  { translatedWord: 'превращенный', translation: 'turned', learned: false },
  { translatedWord: 'фьючерс', translation: 'futures', learned: false },
  { translatedWord: 'кажется', translation: 'seems', learned: false },
  { translatedWord: 'хранение', translation: 'storage', learned: false },
  { translatedWord: 'Французский язык', translation: 'French', learned: false },
  { translatedWord: 'выгода', translation: 'benefit', learned: false },
  { translatedWord: 'запланированный', translation: 'planned', learned: false },
  { translatedWord: 'Сторона', translation: 'side', learned: false },
  { translatedWord: 'инфляция', translation: 'inflation', learned: false },
  { translatedWord: 'читать', translation: 'read', learned: false },
  { translatedWord: 'рука', translation: 'hand', learned: false },
  { translatedWord: 'построенный', translation: 'built', learned: false },
  { translatedWord: 'индустриальный', translation: 'industrial', learned: false },
  { translatedWord: 'стратегия', translation: 'strategy', learned: false },
  { translatedWord: 'власти', translation: 'authorities', learned: false },
  { translatedWord: 'ожидает', translation: 'expects', learned: false },
  { translatedWord: 'Комитет', translation: 'Committee', learned: false },
  { translatedWord: 'распределение', translation: 'distribution', learned: false },
  { translatedWord: 'адрес', translation: 'address', learned: false },
  { translatedWord: 'автомобили', translation: 'cars', learned: false },
  { translatedWord: 'особенно', translation: 'especially', learned: false },
  { translatedWord: 'человек', translation: 'human', learned: false },
  { translatedWord: 'центр', translation: 'center', learned: false },
  { translatedWord: 'юридический', translation: 'legal', learned: false },
  { translatedWord: 'документы', translation: 'documents', learned: false },
  { translatedWord: 'пополудни.', translation: 'afternoon', learned: false },
  { translatedWord: 'принесенный', translation: 'brought', learned: false },
  { translatedWord: 'эффективный', translation: 'effective', learned: false },
  { translatedWord: 'отпуск', translation: 'vacation', learned: false },
  { translatedWord: 'газета', translation: 'newspaper', learned: false },
  { translatedWord: 'быстро', translation: 'quickly', learned: false },
  { translatedWord: 'примечания', translation: 'notes', learned: false },
  { translatedWord: 'письменный', translation: 'written', learned: false },
  { translatedWord: 'строить', translation: 'build', learned: false },
  { translatedWord: 'Западный', translation: 'Western', learned: false },
  { translatedWord: 'урожай', translation: 'harvest', learned: false },
  { translatedWord: 'Управление', translation: 'Management', learned: false },
  { translatedWord: 'уменьшенный', translation: 'reduced', learned: false },
  { translatedWord: 'принести', translation: 'bring', learned: false },
  { translatedWord: 'независимый', translation: 'independent', learned: false },
  { translatedWord: 'кредиты', translation: 'loans', learned: false },
  { translatedWord: 'перемещенный', translation: 'moved', learned: false },
  { translatedWord: 'телефон', translation: 'phone', learned: false },
  { translatedWord: 'остается', translation: 'remains', learned: false },
  { translatedWord: 'передача', translation: 'transfer', learned: false },
  { translatedWord: 'одобренный', translation: 'approved', learned: false },
  { translatedWord: 'просто', translation: 'simply', learned: false },
  { translatedWord: 'девять', translation: 'nine', learned: false },
  { translatedWord: 'чувство', translation: 'feeling', learned: false },
];
